config/routes.rb
  get '/users/:username', to: redirect('/@%{username}'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:username/with_replies', to: 'accounts#show', as: :short_account_with_replies
  get '/@:username/media', to: 'accounts#show', as: :short_account_media
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
  get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status

  get  '/interact/:id', to: 'remote_interaction#new', as: :remote_interaction
  post '/interact/:id', to: 'remote_interaction#create'

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :notifications, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show, :create]
    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]
    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resource :follower_domains, only: [:show, :update]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :update]

    resources :sessions, only: [:destroy]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]

  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  # Remote follow
  resource :remote_unfollow, only: [:create]
  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :subscriptions, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create, :show, :destroy]
    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resource :settings, only: [:edit, :update]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index] do
      collection do
        post :resubscribe
      end
    end

    resources :reports, only: [:index, :show, :update] do
      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show] do
      member do
        post :subscribe
        post :unsubscribe
        post :enable
        post :disable
        post :redownload
        post :remove_avatar
        post :memorialize
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :silence, only: [:create, :destroy]
      resource :suspension, only: [:new, :create, :destroy]
      resources :statuses, only: [:index, :create, :update, :destroy]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy] do
      member do
        post :copy
        post :enable
        post :disable
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
          get :card
        end
      end

      namespace :timelines do
        resource :direct, only: :show, controller: :direct
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]

      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      get '/search', to: 'search#index', as: :search

      resources :follows,      only: [:create]
      resources :media,        only: [:create, :update]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index]
      resources :favourites,   only: [:index]
      resources :reports,      only: [:create]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
          post :dismiss # Deprecated
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end
    end

    namespace :v2 do
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action :set_body_classes
  before_action :set_instance_presenter, only: [:show, :more, :terms]

  def show
    serializable_resource = ActiveModelSerializers::SerializableResource.new(InitialStatePresenter.new(initial_state_params), serializer: InitialStateSerializer)
    @initial_state_json   = serializable_resource.to_json
  end

  def more
    render layout: 'public'
  end

  def terms
    render layout: 'public'
  end

  private

  def new_user
    User.new.tap(&:build_account)
  end

  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @body_classes = 'with-modals'
  end

  def initial_state_params
    {
      settings: { known_fediverse: Setting.show_known_fediverse_at_about_page },
      token: current_session&.token,
    }
  end
end

app/views/about/_features.html.haml
.features-list
  .features-list__row
    .text
      %h6= t 'about.features.real_conversation_title'
      = t 'about.features.real_conversation_body'
    .visual
      = fa_icon 'fw comments'
  .features-list__row
    .text
      %h6= t 'about.features.not_a_product_title'
      = t 'about.features.not_a_product_body'
    .visual
      = fa_icon 'fw users'
  .features-list__row
    .text
      %h6= t 'about.features.within_reach_title'
      = t 'about.features.within_reach_body'
    .visual
      = fa_icon 'fw mobile'
  .features-list__row
    .text
      %h6= t 'about.features.humane_approach_title'
      = t 'about.features.humane_approach_body'
    .visual
      = fa_icon 'fw leaf'

app/views/about/_forms.html.haml
- if @instance_presenter.open_registrations
  = render 'registration'
- else
  = link_to t('auth.register_elsewhere'), 'https://joinmastodon.org', class: 'button button-primary'

  .closed-registrations-message
    - if @instance_presenter.closed_registrations_message.blank?
      %p= t('about.closed_registrations')
    - else
      = @instance_presenter.closed_registrations_message.html_safe

.separator-or
  %span= t('auth.or')

= link_to t('auth.login'), new_user_session_path, class: 'button button-alternative-2 webapp-btn'

app/views/about/_links.html.haml
.container-alt.links
  .brand
    = link_to root_url do
      = image_tag asset_pack_path('logo_full.svg'), alt: 'Mastodon'

  %ul.nav
    %li
      - if user_signed_in?
        = link_to t('settings.back'), root_url, class: 'webapp-btn'
      - else
        = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
    %li= link_to t('about.about_this'), about_more_path
    %li
      = link_to 'https://joinmastodon.org/' do
        = "#{t('about.other_instances')}"
        %i.fa.fa-external-link{ style: 'padding-left: 5px;' }

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  = f.simple_fields_for :account do |account_fields|
    = account_fields.input :username, wrapper: :with_label, autofocus: true, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username') }, append: "@#{site_hostname}", hint: false

  = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false
  = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off' }, hint: false
  = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false

  .actions
    = f.button :button, t('auth.register'), type: :submit, class: 'button button-primary'

  %p.hint.subtle-hint=t('auth.agreement_html', rules_path: about_more_path, terms_path: terms_path)

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  = javascript_pack_tag 'public', integrity: true, crossorigin: 'anonymous'
  = render partial: 'shared/og'

.grid-3
  .column-0
    .public-account-header.public-account-header--no-bar
      .public-account-header__image
        = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('preview.jpg'), alt: @instance_presenter.site_title, class: 'parallax'

  .column-1
    .landing-page__call-to-action{ dir: 'ltr' }
      .row
        .row__information-board
          .information-board__section
            %span= t 'about.user_count_before'
            %strong= number_with_delimiter @instance_presenter.user_count
            %span= t 'about.user_count_after', count: @instance_presenter.user_count
          .information-board__section
            %span= t 'about.status_count_before'
            %strong= number_with_delimiter @instance_presenter.status_count
            %span= t 'about.status_count_after', count: @instance_presenter.status_count
        .row__mascot
          .landing-page__mascot
            = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('elephant_ui_plane.svg'), alt: ''

  .column-2
    .landing-page__information.contact-widget
      %p
        %strong= t 'about.administered_by'

      = account_link_to(@instance_presenter.contact_account)

      - if @instance_presenter.site_contact_email.present?
        %p.contact-widget__mail
          %strong
            = succeed ':' do
              = t 'about.contact'
          %br/
          = mail_to @instance_presenter.site_contact_email, nil, title: @instance_presenter.site_contact_email

  .column-3
    .box-widget
      .rich-formatting= @instance_presenter.site_extended_description.html_safe.presence || t('about.extended_description_html')

app/views/about/show.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %link{ rel: 'canonical', href: about_url }/
  %script#initial-state{ type: 'application/json' }!= json_escape(@initial_state_json)
  = javascript_pack_tag 'about', integrity: true, crossorigin: 'anonymous'
  = render partial: 'shared/og'

.landing-page.alternative
  .container
    .grid
      .column-0
        .brand
          = link_to root_url do
            = image_tag asset_pack_path('logo_full.svg'), alt: 'Mastodon'

      - if Setting.timeline_preview
        .column-1
          .landing-page__forms
            .brand
              = link_to root_url do
                = image_tag asset_pack_path('logo_full.svg'), alt: 'Mastodon'

            = render 'forms'

      - else
        .column-1.non-preview
          .landing-page__forms
            .brand
              = link_to root_url do
                = image_tag asset_pack_path('logo_full.svg'), alt: 'Mastodon'

            = render 'forms'

      - if Setting.timeline_preview
        .column-2
          .landing-page__hero
            = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('preview.jpg'), alt: @instance_presenter.site_title

          .landing-page__information
            .landing-page__short-description
              .row
                .landing-page__logo
                  = image_tag asset_pack_path('logo_transparent.svg'), alt: 'Mastodon'

                %h1
                  = @instance_presenter.site_title
                  %small!= t 'about.hosted_on', domain: content_tag(:span, site_hostname)

              %p= @instance_presenter.site_description.html_safe.presence || t('about.generic_description', domain: site_hostname)

          .landing-page__call-to-action{ dir: 'ltr' }
            .row
              .row__information-board
                .information-board__section
                  %span= t 'about.user_count_before'
                  %strong= number_with_delimiter @instance_presenter.user_count
                  %span= t 'about.user_count_after', count: @instance_presenter.user_count
                .information-board__section
                  %span= t 'about.status_count_before'
                  %strong= number_with_delimiter @instance_presenter.status_count
                  %span= t 'about.status_count_after', count: @instance_presenter.status_count
              .row__mascot
                .landing-page__mascot
                  = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('elephant_ui_plane.svg'), alt: ''

      - else
        .column-2.non-preview
          .landing-page__hero
            = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('preview.jpg'), alt: @instance_presenter.site_title

          .landing-page__information
            .landing-page__short-description
              .row
                .landing-page__logo
                  = image_tag asset_pack_path('logo_transparent.svg'), alt: 'Mastodon'

                %h1
                  = @instance_presenter.site_title
                  %small!= t 'about.hosted_on', domain: content_tag(:span, site_hostname)

              %p= @instance_presenter.site_description.html_safe.presence || t('about.generic_description', domain: site_hostname)

          .landing-page__call-to-action
            .row
              .row__information-board
                .information-board__section
                  %span= t 'about.user_count_before'
                  %strong= number_with_delimiter @instance_presenter.user_count
                  %span= t 'about.user_count_after', count: @instance_presenter.user_count
                .information-board__section
                  %span= t 'about.status_count_before'
                  %strong= number_with_delimiter @instance_presenter.status_count
                  %span= t 'about.status_count_after', count: @instance_presenter.status_count
              .row__mascot
                .landing-page__mascot
                  = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('elephant_ui_plane.svg'), alt: ''

      - if Setting.timeline_preview
        .column-3
          #mastodon-timeline{ data: { props: Oj.dump(default_props) } }

      - if Setting.timeline_preview
        .column-4.landing-page__information
          .landing-page__features
            .features-list
              %div
                %h3= t 'about.what_is_mastodon'
                %p= t 'about.about_mastodon_html'
              %div.contact
                %h3= t 'about.administered_by'
                = account_link_to(@instance_presenter.contact_account, link_to(t('about.learn_more'), about_more_path, class: 'button button-alternative'))

            = render 'features'

            .landing-page__features__action
              = link_to t('about.learn_more'), 'https://joinmastodon.org/', class: 'button button-alternative'

          .landing-page__footer
            %p
              = link_to t('about.source_code'), @instance_presenter.source_url
              = " (#{@instance_presenter.version_number})"

      - else
        .column-4.non-preview.landing-page__information
          .landing-page__features
            .features-list
              %div
                %h3= t 'about.what_is_mastodon'
                %p= t 'about.about_mastodon_html'
              %div.contact
                %h3= t 'about.administered_by'
                = account_link_to(@instance_presenter.contact_account, link_to(t('about.learn_more'), about_more_path, class: 'button button-alternative'))

            = render 'features'

            .landing-page__features__action
              = link_to t('about.learn_more'), 'https://joinmastodon.org/', class: 'button button-alternative'

          .landing-page__footer
            %p
              = link_to t('about.source_code'), @instance_presenter.source_url
              = " (#{@instance_presenter.version_number})"

#modal-container

app/views/about/terms.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.grid
  .column-0
    .box-widget
      .rich-formatting= @instance_presenter.site_terms.html_safe.presence || t('terms.body_html')
  .column-1
    = render 'application/sidebar'